In [19]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest
from scipy.stats import spearmanr
from scipy import stats
from scipy.stats import chi2_contingency
from scipy.stats import ttest_ind
from scipy.stats import f_oneway
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()
mean_values = df.mean()
mean_values
median_values = df.median()
median_values
mode_values = df.mode().iloc[0]
mode_values

sepal length (cm)    5.0
sepal width (cm)     3.0
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64

In [3]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
range_values = df.max() - df.min()
range_values
variance_values = df.var()
variance_values
std_values = df.std()
std_values
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
IQR

sepal length (cm)    1.3
sepal width (cm)     0.5
petal length (cm)    3.5
petal width (cm)     1.5
dtype: float64

In [6]:
iris = load_iris()
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)
skewness_values = df.skew()
print(skewness_values)
kurtosis_values = df.kurt()
kurtosis_values

sepal length (cm)    0.314911
sepal width (cm)     0.318966
petal length (cm)   -0.274884
petal width (cm)    -0.102967
dtype: float64

sepal length (cm)   -0.552064
sepal width (cm)     0.228249
petal length (cm)   -1.402103
petal width (cm)    -1.340604
dtype: float64

In [8]:
iris = load_iris()
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)
corr_matrix = df.corr(method='pearson')
corr_matrix

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.117570,0.871754,0.817941
sepal width (cm),-0.117570,1.000000,-0.428440,-0.366126
petal length (cm),0.871754,-0.428440,1.000000,0.962865
petal width (cm),0.817941,-0.366126,0.962865,1.000000

In [10]:
iris = load_iris()
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)
corr_matrix = df.corr(method='spearman')
corr_matrix

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
sepal length (cm),1.000000,-0.166778,0.881898,0.834289
sepal width (cm),-0.166778,1.000000,-0.309635,-0.289032
petal length (cm),0.881898,-0.309635,1.000000,0.937667
petal width (cm),0.834289,-0.289032,0.937667,1.000000

In [12]:
data = pd.DataFrame({
    'Gender':['M','F','M','F','M'],
    'Purchase':['Yes','No','Yes','No','Yes']
})
table = pd.crosstab(
    data['Gender'],
    data['Purchase']
)
chi2, p, dof, expected = chi2_contingency(table)
print("Chi-Square Statistic:", chi2)
print("P-value:", p)

Chi-Square Statistic: 1.7013888888888886
P-value: 0.19210644086793857

In [14]:
group1 = [12,15,14,10,13]
group2 = [22,25,24,20,23]
t_stat, p_value = ttest_ind(
    group1,
    group2
)
print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -8.219949365267864
P-value: 3.590458475542753e-05

In [16]:
group1 = [10,12,11]
group2 = [20,22,19]
group3 = [30,31,29]
f_stat, p_value = f_oneway(
    group1,
    group2,
    group3
)
print("F-statistic:", f_stat)
print("P-value:", p_value)

F-statistic: 187.46153846153928
P-value: 3.907886125506085e-06

In [18]:
sample = np.array(
    [10,12,11,13,12,14,15]
)
z_stat, p_value = ztest(
    sample,
    value=12
)
print("Z-statistic:", z_stat)
print("P-value:", p_value)

Z-statistic: 0.6599120175960902
P-value: 0.50931029171949

In [20]:
data = [10,12,11,13,14,100]
z_scores = np.abs(
    stats.zscore(data)
)
outliers = np.where(
    z_scores > 3
)
print("Outlier Index:", outliers)

Outlier Index: (array([], dtype=int64),)

In [23]:
df = pd.DataFrame({
    'Values':[10,12,11,13,14,100]
})

Q1 = df['Values'].quantile(0.25)
Q3 = df['Values'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[
    (df['Values'] < lower) |
    (df['Values'] > upper)
]
print("Outliers:")
print(outliers)

Outliers:
   Values
5     100

In [24]:
data = np.array([
    10,12,11,13,14,100
])
mean = np.mean(data)
std = np.std(data)
G = np.max(
    np.abs(data - mean)
) / std
print("Grubbs Statistic:", G)

Grubbs Statistic: 2.2343374977017003